### ISSUE TITLE
be able to generate correlated variables

### ISSUE THREAD

**Issue by peterhurford** [rethinkpriorities/squigglepy#24]
One potential idea: https://stackoverflow.com/questions/18683821/generating-random-correlated-x-and-y-points-using-numpy

**Comment by agucova** [comment]
Instead of hardcoding it for certain distributions, we can apply the more general Cholesky transformation on sampling. See [here](https://en.wikipedia.org/wiki/Cholesky_decomposition#Monte_Carlo_simulation). I can give this a try, but I'm not statistician, and we might want some feedback from one.

**Comment by agucova** [comment]
@peterhurford what do you think?

**Comment by peterhurford** [comment]
@agucova Looks awesome!

**Comment by peterhurford** [comment]
https://github.com/rethinkpriorities/squigglepy/issues/45 may be related

**Comment by agucova** [comment]
@peterhurford I've talked with Jaime from Epoch, and they've told me they've been using copula-based methods as well. The way I've implemented the Iman-Conover method should be mathematically equivalent to the normal copula method, but copulas can be more flexible in certain situations.
