### ISSUE TITLE
Be more restrictive with Python version support + test Python support

### ISSUE THREAD

**Issue by peterhurford** [rethinkpriorities/squigglepy#30]
Currently aiming to support python 3.7 or higher

I would at least go to python 3.8; and ideally 3.9 or 3.10

Also we should have a testing framework to check this

**Comment by agucova** [comment]
You can probably add `pytest` to a GitHub Actions workflow, and have a [matrix](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs) that runs the tests on each support version. See [here](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python).

**Comment by peterhurford** [comment]
Per https://twitter.com/peterwildeford/status/1667673664601432068 I think we can safely go with 3.9 as the minimum version

**Comment by peterhurford** [comment]
In progress https://github.com/rethinkpriorities/squigglepy/pull/32
