### ISSUE TITLE
improve `import squigglepy as sq` runtime

### ISSUE THREAD

**Issue by peterhurford** [rethinkpriorities/squigglepy#35]
Currently takes 0.5sec to load

Could improve by having some imports only load dynamically.

Could also improve by not loading all of scipy.

**Comment by peterhurford** [comment]
One part https://github.com/rethinkpriorities/squigglepy/pull/34 though it doesn't actually help much

**Comment by agucova** [comment]
Fixed by https://github.com/rethinkpriorities/squigglepy/pull/36
